# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_H-kKoKtUSO5WFgAzXT-pBN-9DCGHrg
"""

def computer_guess_g():
  low = 1
  high = 100 #guess from 1 to 100

  print("Think of a number between 1 and 100")
  feedback = None
  guess = None

  while feedback != "c":
    guess = (high + low) // 2
    feedback = input(f"Is {guess} the number you thought? say h for higher, l for lower and c for correct!" ).lower()

    if feedback == "h":
      low = guess+1 # if higher low = previous guess


    if feedback == "l":
      high = guess-1 #if lower high = previous guess

    elif feedback =="c":
     print("I did it!")

    elif high < low:
      print("Fuck you")
      break
computer_guess_g()

def computer_guess_g():
    low = 1
    high = 100

    print("Think of a number between 1 and 100")
    feedback = None
    guess_history = []

    while feedback != "c":
        # 1. THE SANITY CHECK: Check for cheating BEFORE guessing
        if low > high:
            print("Wait... that's impossible. You're cheating!")
            break

        guess = (high + low) // 2
        feedback = input(f"Is {guess} your number? (h/l/c): ").lower()

        # 2. THE LOGIC CHAIN: Use 'elif' for all branches
        if feedback == "h":
            low = guess + 1
            guess_history.append(guess)
        elif feedback == "l":
            high = guess - 1
            guess_history.append(guess)
        elif feedback == "c":
            print(f"I did it! Your number was {guess}.")
            print("failed attempts", guess_history)

        else:
            print("Please enter h, l, or c.")

computer_guess_g()

def get_valid_int(prompt: str) -> int:
    """Repeatedly asks for input until a valid integer is provided."""
    while True:
        user_input = input(prompt)
        try:
            return int(user_input)
        except ValueError:
            print("❌ Invalid! Please enter a whole number.")

start = None
end = None

def computer_guess_g(low: int, high: int):
    """The game logic you've already mastered goes here."""
    # ... (Your binary search code) ...
    def number_guess_g():
      high = start
      low = end
      guesses = []
      feedback = None

      while feedback != "c":
        guess = (high + low) //2
        feedback = input(f"is {guess} the right answer? h for higher, l for lower and c for correct")

        if feedback == "l":
         high = guess- 1

        if feedback == "h":
          low = guess + 1

    print(f"I'll find your number between {low} and {high}!")

def main():
    print("--- Welcome to the Pro Bot ---")
    # Using our validator to get the range
    start = get_valid_int("Enter the bottom of the range: ")
    end = get_valid_int("Enter the top of the range: ")

    # Passing those numbers into the game
    computer_guess_g(start, end)

# This is the 'Start' button for the whole program
main()

class Wallet:

  def __init__(self, owner):
    self.owner = owner_name

    self.balances = {}
    currency = "USD"
    amount = 30

    if currency in self.balances:
      self.balances[currency] += amount
    else:
      self.balances[currency] = amount

  def add_money(self, currency, amount):
    if currency in self.balances:
      self.balances[currency] += amount
    else:
      self.balances[currency] = amount

  def spend_money(self, currency, amount):

my_wallet = Wallet("Alex")
my_wallet.add_money("USD", 100)
my_wallet.spend_money("USD", 20)

class Wallet:
  def __init__(self, owner_name):
    self.owner = owner_name
    self.balance = {}

  def add_money(self, currency, amount):
    if currency in self.balance:
      self.balance[currency] += amount
    else:
      self.balance[currency] = amount

  def spend_money(self, currency, amount):
    if currency in self.balance and self.balance[currency] > amount:
      self.balance[currency] -= amount
    else:
      print("not enough money")

my_wallet = Wallet("Alex")
my_wallet.add_money("USD", 100)
my_wallet.spend_money("USD", 20)
print(my_wallet.balance)

"""Exercise 2: The "Library System" (Lists of Objects)
This is a classic FAANG interview-style problem. You aren't just managing data; you're managing relationships between data.

The Setup: Create two classes: Book and Library.

The Book Class: Should have title, author, and is_checked_out (a boolean).

The Library Class: Should have a list of Book objects.

The Task: Write a method in Library called find_by_author(name) that loops through the list and returns all books by that author.

The SWE Goal: Practice "Composition"—putting one object inside another.
"""

class Library:
  def __init__(self):
    self.books = []

  def add_book(self, book):
    self.books.append(book)
    print("added", book.title)

  def list_available_books(self):
    print("--- Available Books ---")
    for b in self.books:
        if b.is_checked_out == False:
            print(f"{b.title} by {b.author}")

class Book:
  def __init__(self, title, author):
    self.title = title
    self.author = author
    self.is_checked_out = False

  def check_out(self):
    self.is_checked_out = True
    print(f"{self.title} has been checked out")

  def return_book(self):
    self.is_checked_out = False
    print(f"{self.title} has been returned")

my_lib = Library()

book1 = Book("1984", "George Orwell")

my_lib.add_book(book1)
print(book1.is_checked_out)
my_lib.list_available_books()

book1.check_out()
print(book1.is_checked_out)
my_lib.list_available_books()

"""The Goal: You have a big list of items, and you need to create a dictionary that tells you how many of each item exists."""

# Your starting data
raw_items = ["apple", "banana", "apple", "orange", "banana", "apple", "kiwi"]

def count_items(items_list):
  counts = {}

  for i in items_list:
    if i in counts:
      counts[i] += 1
    else:
      counts[i] = 1

  return counts

result = count_items(raw_items)
print(result)
# Your goal is to create this:
# {"apple": 3, "banana": 2, "orange": 1, "kiwi": 1}

# Your starting data
raw_items = ["apple", "banana", "apple", "orange", "banana", "apple", "kiwi"]

def count_items(items):
  counts = {}
  for i in items:
    counts[i] = counts.get(i, 0) + 1
  return counts

result = count_items(raw_items)
print(result)

import json

dic = {"letters" : 100, "words": 22, "Text": 1}
with open("dictionary.json", "w") as b:
  json.dump(dic, b, indent=3)

print("saved")

with open("dictionary.json", "r") as c:
  my_data = json.load(c)

print(my_data)

import json
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def to_dict(self):
        # Translate the object into a simple dictionary JSON understands
        return {"title": self.title, "author": self.author}
        with open("Library.json", "w") as b:
          json.dump(Book, b)

import json
class Player:
  def __init__(self, name, score):
    self.name = name
    self.score = score

  players = [Player("Alex", 9000), Player("Sam", 8500), Player("Casey", 9200)]

  save_ready_list = []
  for i in players:
    dict_version = i.to_dict()
    save_ready_list.append(dict_version)

with open("players.json", "w") as b:
  json.dump(save_ready_list, b)

with open("players.json", "r")  as c:
  loaded_team = json.load(c)


print(loaded_team[0]["name"])

import json

class Player:
  def __init__(self, name, score):
    self.name = name
    self.score = score

  def to_dict(self):
    return {"name": self.name, "score": self.score}

#create the objects
players = [Player("Alex", 9000), Player("Sam", 8500), Player("Casey", 9200)]

#transform objects into a list of dictionaries
save_ready_list = []
for i in players:
  dict_version = i.to_dict()
  save_ready_list.append(dict_version)

#save the file
with open("players.json", "w") as b:
  json.dump(save_ready_list, b)

#load the file
with open("players.json", "r") as c:
  json.load(c)

print(save_ready_list[2]["score"])

import json

players = [{"name": "Alex", "score": 9000},
           {"name": "Sam", "score": 8500},
           {"name": "Casey", "score": 9200},
           {"name": "Jordan", "score": 7800}]

#create the file
with open("players.json", "w") as b:
  json.dump(players, b)

# Angenommen, die Datei existiert schon...
with open("players.json", "r") as f:
    team_data = json.load(f)

# HIER DEINE LOGIK:
highest_score = 0
best_player = ""

for p in team_data:
    # 1. Prüfe, ob p["score"] größer ist als highest_score
  if p["score"] > highest_score:
    highest_score = p["score"]
    best_player = p["name"]

    # 2. Wenn ja, update die Variablen
#uptade der Name

print(f"Der MVP ist {best_player} mit {highest_score} Punkten.")

import json
#versuch Datei library.json zu öffnen

filename = "library.json"
try:
  with open(filename, "r") as b:
    library = json.load(b)

except (FileNotFoundError, json.JSONDecodeError):
  library = []

#füge Buch des benutzers hinzu
user_input = input("gib einen neuen Buchnamen" )
library.append(user_input)

with open("library.json", "w") as b:
  json.dump(library, b)

import json

filename = "library.json"

# 1. Einmaliges Laden am Anfang
try:
    with open(filename, "r") as f:
        library = json.load(f)
except FileNotFoundError:
    library = []

# 2. Die Endlosschleife für das Menü
while True:
    print("\n--- MEINE BIBLIOTHEK ---")
    print("1. Buch hinzufügen")
    print("2. Bücher anzeigen")
    print("3. Beenden")

    wahl = input("Was möchtest du tun? (1/2/3): ")

    if wahl == "1":
        neu = input("Name des Buches: ")
        library.append(neu)
        # Speichere die Liste direkt nach dem Hinzufügen
        with open(filename, "w") as f:
            json.dump(library, f)

    elif wahl == "2":
        print("\nDeine Bücher:")
        for b in library:
            print(f"- {b}")

    elif wahl == "3":
        print("Bye Bye!")
        break  # Das beendet die Schleife
    else:
        print("Ungültige Eingabe, probier's nochmal.")

import json
library = ["1984", "Brave New World", "The  Hobbit"]

#make the file
with open("library.json", "w") as a:
  json.dump(library, a)

print(library)

#user input
user_input = input("which book do you want?" )

for i in library:
  if user_input == i:
    library.remove(i)

#upload file
with open("library.json", "w") as b:
  json.dump(library, b)

with open("library.json", "r") as c:
  new_lib = json.load(c)

print(new_lib)

import json

filename = "library.json"

# 1. LADEN (Den Stand von gestern holen)
try:
    with open(filename, "r") as f:
        library = json.load(f)
except:
    library = ["1984", "Brave New World", "The Hobbit"]

# 2. LOGIK (Löschen)
user_input = input("Welches Buch soll weg? ")

if user_input in library:
    library.remove(user_input)
    # 3. SPEICHERN (Den neuen Stand sichern)
    with open(filename, "w") as f:
        json.dump(library, f)
    print("Gespeichert!")
else:
    print("Buch nicht gefunden.")

print("Aktuelle Liste:", library)